name: Flutter Build Release APK

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Compilar APK (Flutter 3.47.1)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: test_pipeline_github_actions

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Esto instala exactamente la versión que necesitas de forma nativa en el runner
      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.1' # Cámbialo a '3.47.5' si tu proyecto lo requiere
          channel: 'stable'
          cache: true

      - name: Verificar versión
        run: flutter --version

      - name: Instalar dependencias
        run: flutter pub get

      - name: Compilar APK Release
        run: flutter build apk --release

      - name: Subir Artifact APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: test_pipeline_github_actions/build/app/outputs/flutter-apk/app-release.apk